# Generated by Django 3.1.3 on 2020-12-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='ну это типо погоняло книги', max_length=50, verbose_name='название')),
            ],
        ),
    ]
