# Generated by Django 3.1.3 on 2020-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20201202_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
