# Generated by Django 3.1.3 on 2020-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_auto_20201216_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTale',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
