# Generated by Django 3.1.3 on 2020-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0022_testcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtale',
            name='title',
            field=models.CharField(db_column='title', max_length=50, primary_key=True, serialize=False),
        ),
    ]
