# Generated by Django 3.1.3 on 2020-12-19 08:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0026_auto_20201219_1116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TMPBook',
            new_name='Book',
        ),
    ]
