# Generated by Django 3.1.3 on 2020-12-19 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0027_auto_20201219_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tmp_book',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='likebookuser',
            old_name='tmp_book',
            new_name='book',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='users_like',
            field=models.ManyToManyField(related_name='liked_books', through='manager.LikeBookUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likebookuser',
            unique_together={('user', 'book')},
        ),
    ]
