# Generated by Django 3.1.3 on 2021-01-06 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0029_tableaggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableaggregate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_aggregate', to=settings.AUTH_USER_MODEL),
        ),
    ]
